version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        NODE_ENV: development  # Set the desired environment here (development or production)
    container_name: nestjs-app
    environment:
      - NODE_ENV=development  # Ensure the environment variable matches the build args
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src/app  # Mount the current directory to the container
      - /usr/src/app/node_modules  # Prevent overwriting node_modules with the host's empty directory
    command: npm run start:dev
    user: "node"  # Run as non-root user
