version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: development # Specify the development stage
    container_name: nestjs-app-dev
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
    volumes:
      - .:/usr/src/app # Mount source code for live updates
      - /usr/src/app/node_modules
    command: npm run start:dev # Override CMD for dev mode
    user: "node" # Run as non-root user
    restart: unless-stopped
